version: 2

project_name: cio_cli

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    binary: cio
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - formats: [tar.gz]

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
