package routes

// ResourceDescriptions provides human-readable descriptions of what each
// resource is and how it's commonly used. These appear in the resource-level
// --help output.
var ResourceDescriptions = map[string]string{
	"accounts":                     "Manage your Customer.io account settings, billing, users, and API credentials.",
	"actions":                      "Manage campaign actions (messages, webhooks, etc.) within a campaign workflow. Actions define what happens when a customer enters a step in a campaign.",
	"campaigns":                    "Manage automated messaging campaigns. Campaigns contain triggers, actions, and goals that define customer journeys. Use campaigns to send targeted messages based on customer behavior and attributes.",
	"categories":                   "Manage categories for organizing campaigns and newsletters.",
	"collections":                  "Manage data collections — reusable sets of data (like product catalogs or store locations) that can be referenced in messages via Liquid.",
	"customers":                    "Manage customer profiles — create, update, delete, search, and export people in your workspace. Customers are the recipients of your campaigns and newsletters.",
	"segments":                     "Manage audience segments — groups of customers defined by attribute or event conditions. Segments power campaign entry, newsletter targeting, and reporting.",
	"newsletters":                  "Manage one-time broadcast messages (newsletters). Send emails, push notifications, or SMS to a segment of customers on a schedule.",
	"templates":                    "Manage reusable message templates. Templates can be shared across campaigns, newsletters, and transactional messages.",
	"snippets":                     "Manage reusable content snippets — blocks of Liquid/HTML that can be included across multiple messages. Update once, reflect everywhere.",
	"layouts":                      "Manage email layouts — reusable wrappers (header, footer, styling) applied to email messages.",
	"tags":                         "Manage tags for organizing campaigns, newsletters, segments, and other resources.",
	"domains":                      "Manage sender domains and DNS configuration for email deliverability (SPF, DKIM, DMARC).",
	"deliveries":                   "View and manage message deliveries — the individual messages sent to customers. Filter by campaign, customer, status, and time range.",
	"exports":                      "Manage data exports — download customer data, delivery logs, and other workspace data as CSV files.",
	"imports":                      "Manage data imports — upload customer data from CSV files into your workspace.",
	"identities":                   "Manage sender identities — the email addresses and names used as the 'From' address on outgoing messages.",
	"environments":                 "Manage workspaces (environments) — isolated containers for people, campaigns, and messaging configuration within a Customer.io account.",
	"transactional_messages":       "Manage transactional messages — triggered emails, push, and SMS for order confirmations, password resets, and other 1:1 messages sent via API.",
	"webhooks":                     "Manage webhook configurations — HTTP endpoints that receive event data from Customer.io when messages are sent, opened, clicked, etc.",
	"webhook_configurations":       "Manage webhook endpoint configurations for receiving Customer.io event data.",
	"objects":                      "Manage custom objects — non-person entities (companies, orders, products) that can be related to customers.",
	"object_types":                 "Manage object type definitions — the schema for custom objects (name, slug, attributes).",
	"relationships":                "Manage relationships between customers and objects. Relationships let you associate customers with companies, orders, or other entities.",
	"subscription_topics":          "Manage subscription topics — the categories customers can opt in/out of (e.g., Marketing, Product Updates).",
	"subscription_center_settings": "Manage subscription center settings — configure the hosted preference page where customers manage their subscriptions.",
	"events":                       "Track and manage customer events — actions customers take that can trigger campaigns or update profiles.",
	"attributes":                   "View and manage customer attributes — the data fields stored on customer profiles.",
	"audit_logs":                   "View audit logs — a record of changes made to your workspace by team members and API integrations.",
	"roles":                        "Manage team member roles and permissions within your account.",
	"users":                        "Manage team members (users) who have access to your Customer.io account.",
	"billing":                      "Manage billing, payment methods, invoices, and plan changes for your account.",
	"integrations":                 "Manage third-party integrations — connect Customer.io with external services for data sync and messaging.",
	"copilot":                      "Customer.io AI Copilot — generate, analyze, and improve message content using AI.",
	"search":                       "Search across customers, campaigns, and other resources in your workspace.",
	"metrics":                      "View performance metrics for campaigns, actions, and newsletters.",
	"data_index":                   "View the data index — a catalog of all customer attributes and events tracked in your workspace.",
	"previews":                     "Preview message content with sample data before sending.",
	"custom_forms":                 "Manage custom form configurations for collecting customer data.",
	"credentials":                  "Manage integration credentials — API keys and tokens for third-party services.",
	"in_app":                       "Manage in-app messages — messages displayed inside your application to logged-in users.",
	"in_app_broadcasts":            "Manage in-app broadcast messages — one-time in-app messages sent to a segment.",
	"sms":                          "Manage SMS configuration — phone numbers, Twilio integration, and SMS-specific settings.",
	"goals":                        "Manage campaign goals — conversion events that measure the success of your campaigns.",
	"backfills":                    "View and manage data backfill jobs — background tasks that reprocess historical data.",
	"saved_rows":                   "Manage saved rows for the drag-and-drop email editor.",
	"subjects":                     "View email subject line data.",
	"suppressions":                 "Manage email suppressions — bounced, unsubscribed, and complained addresses that are blocked from receiving messages.",
	"url_params":                   "Manage URL parameters — UTM and custom parameters automatically appended to links in messages.",
	"whitelisted_ips":              "Manage IP allowlists for webhook and API security.",

	// CDP Pipelines resources
	"sources":                  "Manage CDP data sources — inbound data connections (JavaScript SDK, integrations, etc.) that feed customer data into Customer.io.",
	"destinations":             "Manage CDP destinations — outbound data connections that sync customer data from Customer.io to external tools and warehouses.",
	"available_sources":        "List available CDP source types that can be configured for a workspace.",
	"available_destinations":   "List available CDP destination types that can be configured for a workspace.",
	"reverse_etls":             "Manage reverse ETL pipelines — sync data from your warehouse back into Customer.io.",
	"database_configs":         "Manage database connection configurations for reverse ETL and warehouse integrations.",
	"database_config_ssh_keys": "Manage SSH keys for secure database connections in CDP pipelines.",
	"source_destination":       "Manage source-to-destination mappings in CDP pipelines.",
	"action_destinations":      "Manage CDP action destination manifests and validation.",
	"action_sources":           "Manage CDP action source manifests.",
}
